# Generated by Django 5.2.6 on 2025-10-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_notification_is_sent_notification_send_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='points_awarded',
            field=models.BooleanField(default=False),
        ),
    ]
