# Generated by Django 5.2.6 on 2025-10-27 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_reservation_points_awarded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='free_seats',
            new_name='seats_limit',
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.hall'),
        ),
        migrations.AlterField(
            model_name='section',
            name='preparation_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='section',
            name='sport_type',
            field=models.CharField(choices=[('fitness', 'Fitness'), ('swimming', 'Swimming'), ('yoga', 'Yoga')], default='fitness', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('hall', 'day', 'month', 'year', 'start_time', 'end_time')},
        ),
        migrations.CreateModel(
            name='SectionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.section')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_schedules', to='api.timeslot')),
            ],
            options={
                'unique_together': {('section', 'timeslot')},
            },
        ),
    ]
