# Generated by Django 5.2.6 on 2025-12-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_premium_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='bonus_multiplier',
            field=models.FloatField(default=0.01),
        ),
    ]
